name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      elasticsearch_version:
        description: 'Elasticsearch version'
        required: true

env:
  ECR_REGISTRY: foodison
  ECR_REPOSITORY: elasticsearch-kuromoji

jobs:
  build_and_push:
    name: Build Docker image and push to AWS ECR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Public ECR
      uses: docker/login-action@v2
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.event.inputs.elasticsearch_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ELASTICSEARCH_VERSION=${{ github.event.inputs.elasticsearch_version }}
